var iKEPLang = {
	uploadControll : {	// file controller
		btnDelete : "删除",
		titDelete : "删除",
		lblUploadFile : "文件上载",
		lblAttachFile : "附件",
		altRollup : "所有",
		altRolldown : "折叠",
		lblFilePerMaxSize : "每个文件最大容量 : %w",
		selectFiles : "文件",
		filter : {txt:"文本文件", img:"影像档", comp:"zip文件", doc:"文档文件", mp:"音乐文件", vod:"视频文件", app:"程序文件", all:"所有的文件"},
		plupload : {
			caption : "请选择要上传的文件.",
			description : "选择该文件后 \"上载\"按下按钮.",
			lblFileName : "文件名",
			lblStatus : "州",
			lblSize : "容量",
			btnAddFiles : "添加文件",
			btnStopUpload : "停止",
			noticeUploading : '%d/%d 提交',
			dragComment : "你可以拖动一个文件浏览器等.",
			errExtension : "文件扩展名错误 : ",
			errSize : "文件大小错误 : ",
			errInit : "初始化错误",
			errHttp : "连接到服务器时出错",
			errSecurity : "安全错误",
			btnStartUpload: "上载"
		},
		errZeroSize : "选定的文件的容量包含零长度的文件.\n\n请删除该文件.",
		errTotalSizeOver : "%w 是允许上传的整体能力.",
		errMaxFileSize : "每个文件的最大容量 : %w",
		lblNoAttachment : "没有附件"
	},
	datepicker : {	// jquery ui datepicker
		langCode : "ch",
		btnClose : "关闭",
		btnPrev : "向前",
		btnNext : "下个月",
		btnCurrentDate : "今日",
		lblMonthNames : ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
		lblMonthNamesShort : ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
		lblDayNames : ["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],
		lblDayNamesShort: ["日","一","二","三","四","五","六"],
		lblDayNamesMin: ["日","一","二","三","四","五","六"],
		lblYear : "年"
	},
	userContextMenu : {
		close : "关闭",
		profile : "轮廓",
		sms : "短信",
		message : "讯息"
	},
	tagging : {	// jquery ui tagging
		required : "请输入您的标签.",
		maxlength:"100个字符或更少可以进入.",
		tagCount:"标签小于10，请.",
		tagDuplicate:"标签是多余的.",
		tagNotice:"请输入您的标签.",
		save:"保存",
		cancel:"取消",
		edit:"编辑",
		tagWord:"字母/数字，朝鲜语，一个逗号，只有白色的可用空间."
	},
	sms : {
		monthSmsCount : "每月超过派遣的人数. 船舶数量高达{}个月的事情. 请检查并再次尝试.",
		sendSuccess : "传输完成."		
	},
	searchUserGroup : {
		duplicateUser : "该用户已被复制.",
		duplicateGroup : "集团已被复制."
	},
	meetingroom : {
		btnText: {
			save: "存储"
		},
		labelText: {
			daily: "天",
			weekly: "每周",
			monthly: "每周",
			yearly: "岁",
			month: "月",
			date_1: "天",
			dow: "星期几",
			last: "最后",
			lastDate: "最后一天",
			nth: "第二",
			am: "上午",
			pm: "下午",
			schedule: "时间表",
			emptySchedule: "是一个空白日历.",
			alarmTypes: ["邮件", "SMS", "讯息"],
			repeatTypes: ['天', '周', '个月', '年'],
			repeatSchedule: "周期性事件",
			open: "公众",
			noopen: "私人",
			every: "一切",
			unit: "每",
			from: "从",
			untilRepeat: "重复",
			forever: "无限循环",
			beforeMin: "分钟前",
			unknown: "暂定",
			attendance: "参与",
			noattendance: "缺席",
			allday: "整天",
			holiday: "假期",
			date: "日期",
			add: "额外",
			period: "期间",
			title: "主题",
			allDayFull: "日历天",
			notAllDayFull: "时间表",
			CAT: "类别",
			totalCountDesc: "总 {} 人",
			reason : "原因",
			total : "充分"
		},
		messageText : {
			inputTitle: "请输入标题.",
			inputCycle: "请输入一个重复周期.",
			inputCycleDigits: "数字可以输入.",
			doSendMail: "邮件的参与者和参考字符，您确定要出货?",
			noAddOwnerToParticipant: "注册计划的参与者/谁不能被添加到引用.",
			noUser: "没有这样的用户.",
			noResult: "没有结果.",
			maxTitle: "标题可以达到最大300字符.",
			checkTimePick: "开始时保留必须小于结束时间。",
			noReservePastDate: "你可以不安排会议的最后日期。",
			noReservePastTime: "最后的时间，我们可以不安排会议。",
			noReserveReadyTime : "保留必须是前至少%w分钟。",
			duplicateReserve: "已经包括在预定的时间。",
			availableReserve : "预约是可能的。"
		}
	},
	planner: { // 일정관리
		buttonText: {  // fullCalendar 전용
			prev: "前",
			next: "未来",
			prevYear: "&nbsp;&lt;&lt;&nbsp;",
			nextYear: "&nbsp;&gt;&gt;&nbsp;",
			today: "今日",
			month: "每月",
			week: "每周",
			day: "天",
			listMonth: "表"
		},			
		titleFormat: {	// fullCalendar 전용
			month: 'yyyy.MM',
			week: "yyyy.MM.dd{ ~ MM.dd [yyyy]}",
			day: "yyyy.MM.dd &#40;ddd&#41;"
		},		
		columnFormat: {	// fullCalendar 전용
			month: 'ddd',
			week: "'<span class=num>'dd'</span>' &#40;ddd&#41;",
			day: "'<span class=num>'MM.dd'</span>' &#40;ddd&#41;"
		},		
		btnText: {	// ikep 용
			update: "改性",
			save: "存储",
			remove: "删除",
			scheduleList: "议程",
			ok: "确认",
			cancel: "取消",
			viewReason : "查看私人"
		},
		labelText: {
			daily: "天",
			weekly: "每周",
			monthly: "每周",
			yearly: "岁",
			month: "月",
			date_1: "天",
			dow: "星期几",
			last: "最后",
			lastDate: "最后一天",
			nth: "第二",
			am: "上午",
			pm: "下午",
			schedule: "时间表",
			emptySchedule: "是一个空白日历.",
			alarmTypes: ["邮件", "SMS", "讯息"],
			repeatTypes: ['天', '周', '个月', '年'],
			repeatSchedule: "周期性事件",
			open: "公众",
			noopen: "私人",
			every: "一切",
			unit: "每",
			from: "从",
			untilRepeat: "重复",
			forever: "无限循环",
			beforeMin: "分钟前",
			unknown: "暂定",
			attendance: "参与",
			noattendance: "缺席",
			allday: "整天",
			holiday: "假期",
			date: "日期",
			add: "额外",
			period: "期间",
			title: "主题",
			allDayFull: "日历天",
			notAllDayFull: "时间表",
			CAT: "类别",
			totalCountDesc: "总 {} 人",
			reason : "原因",
			total : "充分"
		},
		titleText: {
			checkParticipant:"参加检查的时间表",
			emptySchedule:"空白时间表",
			emptyTodaySchedule: "No schedules for today",
			companySchedule: "Company schedules",
			mySchedule:"我的日历",
			mandatorSchedule:"委托的 日历",
			teamSchedule:"球队共享的日历",
			userSchedule:"个人用户的日历",
			privateSchedule:"私人日历",
			memberSchedule:"某些成员",
			viewDetailEvent:"附表明细",
			noattendanceTitle:"缺席的书面理由"				
		},
		messageText: {
			inputTitle: "请输入标题.",
			inputCycle: "请输入一个重复周期.",
			inputCycleDigits: "数字可以输入.",
			doSendMail: "邮件的参与者和参考字符，您确定要出货?",
			checkTrustee: "请强制性的名称.",
			emptySchedule: "有没有时间表.",
			emptyTodaySchedule: "注册今天没有事件.",			
			showDetail: "附表详情",
			noUser: "没有这样的用户.",
			noResult: "没有结果.",
			selectHoliday: "请选择要删除的假期.",
			confirmDeleteHoliday: "你确定要删除选定的假期?",
			selectCategory: "请选择要删除的类别.",
			selectCompany: "Select a company-schedule to delete.",
			selectCompanyApprove: "Select a company-schedule to approve.",
			confirmDeleteCategory: "你确定要删除选定的类别？业务类别的类别中删除，改变现有的时间表.",
			confirmDeleteSchedule: "你确定要删除所选的时间表?",
			confirmApproveSchedule: "Proceed to approve the schedule?",
			clickSearchMessage: "注册后点击搜索按钮，在通讯簿.",
			maxTitle: "标题可以达到最大300字符.",
			checkRepeatDay: "请选择每周重复的一天.",
			confirmDeleteMantator: "你确定要删除强制性?",
			noAddOwnerToParticipant: "注册计划的参与者/谁不能被添加到引用.",
			repeatUpdateDialogTitle : "修改周期性事件",
			repeatUpdateOptionSelect : "请选择修改选项.",
			repeatDeletDialogTitle : "删除重复事件",
			repeatDeleteOptionSelect : "请选择删除选项.",
			repeatUpdateConfirm : "你想修改为重复的时间表?"
		},
		errorText: {
			unknowError: "失败",
			failUpload: "件上传失败",
			duplicateName: "全国人民都登记在同一假期.",
			duplicateCategoryName: "同一类别的名称注册.",
			eventDeleted : "事已被删除.",
			meetingRoomDuplicate : "会议室已经被预订您的选择。\n\n请选择其他时间或其他会议。"
		}
	},
	mainPortlet : {	//포틀릿
		more : "更多",
		config : "配置",
		reload : "刷新",
		maximize : "大窗口",
		minimize : "隐藏",
		restore : "正常",
		help : "帮助",
		close : "删除",
		titHelpPopup : " 帮助",
		configSuccessMessage : "已成立.",
		configFailMessage : "无法设置.",
		confirmRemoveMessage : "你要删除?",
		personalPortletMessage : "您不可以个人的portlet接口.",
		publicPortletMessage : "在私营部门不能提高公众的portlet.",
		noPage : "该页无法显示."	
	},
	clock : {
		sDayName : ["日","一","二","三","四","五","六"],
		fDayName : ["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],
		sMonthName : ["一","二","三","四","五","六","七","八","九","十","十一","十二"],
		fMonthName : ["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
		am : "上午",
		pm : "下午",
		AM : "上午",
		PM : "下午",
		subscriptYear : "年",
		subscriptMonth : "月",
		subscriptDay : "天"
	},
	gallery : {
		imgCount : "#{cur}/#{tot}"
	},
	ieCheck : {   
		msgCompatible :  "浏览器的 \"兼容性视图\"设置的一些功能可能无法正常工作.<br/>浏览器比IE8兼容性视图模式其他的, 请设置超过.<br/>[<a href=\"#{compatibleUrl}\" traget=\"_blank\">找出如何设置</a>]",
		msgUpgrade : "如果你想使用的浏览器Internet Explorer浏览器，版本8或更高版本，必须使用正常使用.<br/>[<a href=\"#{upgradeUrl}\" traget=\"_blank\">升级</a>]<br/>一万天,如果你已经在使用了IE8开发人员工具的浏览器模式和文件模式到IE8,必须至少设置为.<br/>[<a href=\"#{modeUrl}\" traget=\"_blank\">找出如何设置</a>]"
	}
};