var eventStyle = {
	note_class_type1:	{ background_color:"#ff7f7f", border:"1px solid #dd7f7f" },
	note_class_type2: 	{ background_color:"#ff7fbf", border:"1px solid #dd7faf" },
	note_class_type3: 	{ background_color:"#ff7fff", border:"1px solid #ee7fee" },
	note_class_type4: 	{ background_color:"#bf7fff", border:"1px solid #be7fee" },
	note_class_type5: 	{ background_color:"#7f7fff", border:"1px solid #7f7fdd" },
	note_class_type6: 	{ background_color:"#7fbfff", border:"1px solid #7fafdd" },
	note_class_type7: 	{ background_color:"#7fffff", border:"1px solid #7feeee" },
	note_class_type8: 	{ background_color:"#7fffbf", border:"1px solid #7feeaf" },
	note_class_type9: 	{ background_color:"#7fff7f", border:"1px solid #7fdd7f" },
	note_class_type10: 	{ background_color:"#bfff7f", border:"1px solid #afee7f" },
	note_class_type11: 	{ background_color:"#ffff7f", border:"1px solid #eeee7f" },
	note_class_type12: 	{ background_color:"#ffbf7f", border:"1px solid #eeaf7f" },
	note_class_type13: 	{ background_color:"#ffb7b7", border:"1px solid #eea7a7" },
	note_class_type14: 	{ background_color:"#ffb7db", border:"1px solid #eeb7cb" },
	note_class_type15: 	{ background_color:"#ffb7ff", border:"1px solid #eeb7ee" },
	note_class_type16: 	{ background_color:"#dbb7ff", border:"1px solid #cbb7ee" },
	note_class_type17: 	{ background_color:"#b7b7ff", border:"1px solid #b7b7ee" },
	note_class_type18: 	{ background_color:"#b7dbff", border:"1px solid #b7cbee" },
	note_class_type19: 	{ background_color:"#b7ffff", border:"1px solid #b7eeee" },
	note_class_type20: 	{ background_color:"#b7ffdb", border:"1px solid #b7eecb" },
	note_class_type21: 	{ background_color:"#b7ffb7", border:"1px solid #a7eea7" },
	note_class_type22: 	{ background_color:"#dbffb7", border:"1px solid #cbeeb7" },
	note_class_type23: 	{ background_color:"#ffffb7", border:"1px solid #eeeeb7" },
	note_class_type24: 	{ background_color:"#ffdbb7", border:"1px solid #eecbb7" }
};
